const db = require('../config/db')

db('perfis')
    .map(perfil => perfil.nome)
    .then(res => console.log(res))
    .finally(() => db.destroy())

db('perfis').select('nome', 'id')
    .then(res => console.log(res))
    .finally(() => db.destroy())

db.select('nome', 'id')
    .from('perfis')
    .limit(4).offset(2)
    .then(res => console.log(res))
    .finally(() => db.destroy())

db('perfis')
    // .where({ id: 2 })
    .where('id', '=', 2)
    .where('nome', 'like', '%min%')
    .whereNot({ id: 2 })
    .first()
    .then(res => console.log(res))
    .finally(() => db.destroy())